-- Question 1
-- Display all customer orders with delivery status.

SELECT
    O.OrderID,
    C.FirstName,
    C.LastName,
    O.OrderDate,
    O.ShippedDate,
    CASE
        WHEN O.ShippedDate IS NULL THEN 'Pending'
        ELSE 'Delivered'
    END AS DeliveryStatus
FROM Orders O
INNER JOIN Customers C
    ON O.CustomerID = C.CustomerID
ORDER BY O.OrderDate DESC;

-- Question 2
-- Show the best-selling products.

SELECT
    P.ProductName,
    SUM(OD.Quantity) AS TotalQuantitySold
FROM Products P
INNER JOIN OrderDetails OD
    ON P.ProductID = OD.ProductID
GROUP BY P.ProductName
ORDER BY TotalQuantitySold DESC;

-- Question 3
-- Show the total revenue generated by each product.

SELECT
    P.ProductName,
    SUM(OD.Quantity * OD.UnitPrice) AS TotalRevenue
FROM Products P
INNER JOIN OrderDetails OD
    ON P.ProductID = OD.ProductID
GROUP BY P.ProductName
ORDER BY TotalRevenue DESC;

-- Question 4
-- Show the customers who placed the most orders.

SELECT
    C.FirstName,
    C.LastName,
    COUNT(O.OrderID) AS TotalOrders
FROM Customers C
INNER JOIN Orders O
    ON C.CustomerID = O.CustomerID
GROUP BY
    C.FirstName,
    C.LastName
ORDER BY TotalOrders DESC;

-- Question 5
-- Show high-value customers whose total purchase is greater than 100000.

SELECT
    O.CustomerID,
    C.FirstName,
    C.LastName,
    SUM(OD.Quantity * OD.UnitPrice) AS TotalPurchase
FROM Customers C
INNER JOIN Orders O
    ON C.CustomerID = O.CustomerID
INNER JOIN OrderDetails OD
    ON O.OrderID = OD.OrderID
GROUP BY
    O.CustomerID,
    C.FirstName,
    C.LastName
HAVING SUM(OD.Quantity * OD.UnitPrice) > 100000
ORDER BY TotalPurchase DESC;

-- Question 6
-- Show employees who handled more than 5 orders.

SELECT
    E.EmployeeID,
    E.FirstName,
    E.LastName,
    COUNT(O.OrderID) AS TotalOrdersHandled
FROM Employees E
INNER JOIN Orders O
    ON E.EmployeeID = O.EmployeeID
GROUP BY
    E.EmployeeID,
    E.FirstName,
    E.LastName
HAVING COUNT(O.OrderID) > 5
ORDER BY TotalOrdersHandled DESC;

-- Question 7
-- Show category-wise revenue and classify each category based on total revenue.

SELECT
    C.CategoryName,
    SUM(OD.Quantity * OD.UnitPrice) AS TotalRevenue,
    CASE
        WHEN SUM(OD.Quantity * OD.UnitPrice) >= 500000 THEN 'High Revenue'
        WHEN SUM(OD.Quantity * OD.UnitPrice) >= 200000 THEN 'Medium Revenue'
        ELSE 'Low Revenue'
    END AS RevenueCategory
FROM Categories C
INNER JOIN Products P
    ON C.CategoryID = P.CategoryID
INNER JOIN OrderDetails OD
    ON P.ProductID = OD.ProductID
GROUP BY
    C.CategoryName
ORDER BY
    TotalRevenue DESC;